### ISSUE TITLE
Provide models for group of computer languages.

### ISSUE THREAD

**Issue by acbits** [ibm-granite/granite-code-models#10]
As the title says, is it possible to generate the model for a tiny group of  computer languages like C/C++, Javascript/Typescript, etc?

I guess the model size would be small and people can run them locally without exotic hardware?

**Comment by mayank31398** [comment]
Hi, currently we are not planning on training smaller models.
However, feel free to try the 4-bit GGUF versions of our models.
They are in the same HF collection as the original models.
