### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by nfisher** [ibm-granite/granite-code-models#17]
### What is the expected behavior?

When using llama.cpp server it would be convenient if the prompt matched an appropriate default for the Granite model.

### What is the actual behavior?

Defaults to the llama chat prompts

### Please provide a unit test or code example to demonstrate the problem.

N/A

### Other notes on how to reproduce the issue? Screenshots of your output are also helpful. 

<img width="705" alt="image" src="https://github.com/user-attachments/assets/33743a85-c5fd-42a0-8bbf-4a99336b8060">

### Any possible solutions?

Add at template to llama.cpp

### If the bug is confirmed, would you be willing to submit a PR?

Maybe

**Comment by mayank31398** [comment]
this is the chat template
https://huggingface.co/ibm-granite/granite-3b-code-instruct/blob/0e2b426b339d0a5a987aa6690aca5f7746ca2707/tokenizer_config.json#L179
I would suggest to create an issue in llama.cpp for this
