### ISSUE TITLE
[Question] Can I use transformers/trl modules to instruction-fine-tune Granite models?

### ISSUE THREAD

**Issue by ruilinWho** [ibm-granite/granite-code-models#18]
Dear Authors:
I noticed Granite models are fine-tuned with Dolomite Engine.
I am wondering if I can instruction fine-tune Granite with modules like trl/huggingfac transformers, or I must use Dolomite Engine otherwise I would get a bad performance...
Much thanks!

**Comment by mayank31398** [comment]
I think either of them will work

**Comment by ruilinWho** [comment]
> I think either of them will work

Thank you!
