### ISSUE TITLE
Links within "Finetuning" section pointing to wrong sites 

### ISSUE THREAD

**Issue by dmarley** [ibm-granite/granite-code-models#20]
### Version Information
 - Model Version: granite-code-models
 - Operating System: N/A

### What is the expected behavior?
Links to Dolomite Engine has moved:
from "https://github.com/ibm-granite/dolomite-engine/"
to "https://github.com/IBM/dolomite-engine/"

Need to also update the git clone repository reference

### What is the actual behavior?
see above (update readme)

### Please provide a unit test or code example to demonstrate the problem.
N/A

### Other notes on how to reproduce the issue? Screenshots of your output are also helpful. 
N/A

### Any possible solutions?
Update URL's

### If the bug is confirmed, would you be willing to submit a PR?
YES

**Comment by mayank31398** [comment]
fixed
