### ISSUE TITLE
[Question] When were the knowledge thresholds set?

### ISSUE THREAD

**Issue by Mateleo** [ibm-granite/granite-code-models#8]

**Comment by mayank31398** [comment]
its very hard to give an exact date sadly.
since various sources of data were crawled at different times.

**Comment by Devy99** [comment]
Hi, is it possible to have any upper bound / estimation of the cut-off date? Like the month you started the models training or anything similar.

**Comment by mayank31398** [comment]
We started training the models some time in September last year.

**Comment by Devy99** [comment]
Thanks!
